apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.name }}
spec:
  schedule: "{{ .Values.cronSchedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: concert-watcher
            image: {{ .Values.image.name }}:{{ .Values.image.tag }}
            command:
            - /bin/sh
            - -c
            - /bin/concert-watcher scan --api-key $TICKETMASTER_API_KEY --artist-file /artists --discord-webhook-url $DISCORD_WEBHOOK_URL --ticketmaster-config /config/ticketmaster.yaml --diff --diff-file /data/previous-ids --include-partial-match
            env:
            - name: "TICKETMASTER_API_KEY"
              {{- if .Values.ticketmaster.apiKey.secret }}
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.ticketmaster.apiKey.secret.name }}"
                  key: "{{ .Values.ticketmaster.apiKey.secret.key }}"
              {{- else }}
              value: "{{ .Values.ticketmaster.apiKey.value }}"
              {{- end }}
            - name: "DISCORD_WEBHOOK_URL"
              {{- if .Values.discord.webhookURL.secret }}
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.discord.webhookURL.secret.name }}"
                  key: "{{ .Values.discord.webhookURL.secret.key }}"
              {{- else }}
              value: "{{ .Values.discord.webhookURL.value }}"
              {{- end }}
            volumeMounts:
            - name: artists
              mountPath: /artists
              subPath: artists
            - name: config-map
              mountPath: /config
            - name: data
              mountPath: /data
          volumes:
          - name: config-map
            configMap:
              name: {{ .Values.name }}-config
          - name: artists
            configMap:
              name: {{ .Values.artists.configMap }}
          - name: data
            persistentVolumeClaim:
              claimName: {{ .Values.name }}-pvc
          restartPolicy: Never
