apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.name }}
spec:
  schedule: "{{ .Values.cronSchedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: concert-watcher
            image: {{ .Values.image.name }}:{{ .Values.image.tag }}
            command:
            - /bin/sh
            - -c
            - /bin/concert-watcher scan --api-key $TICKETMASTER_API_KEY --artist-file /config/artists --discord-webhook-url $DISCORD_WEBHOOK_URL --ticketmaster-config /config/ticketmaster.yaml --diff --diff-file /data/previous-ids --include-partial-match
            env:
            - name: "TICKETMASTER_API_KEY"
              value: "{{ .Values.ticketmaster.apiKey }}"
            - name: "DISCORD_WEBHOOK_URL"
              value: "{{ .Values.discord.webhookURL }}"
            volumeMounts:
            - name: config-map
              mountPath: /config
            - name: data
              mountPath: /data
          volumes:
          - name: config-map
            configMap:
              name: {{ .Values.name }}-config
          - name: data
            persistentVolumeClaim:
              claimName: {{ .Values.name }}-pvc
          restartPolicy: Never
