name: concert-watch
image: concert-watch:latest

cronSchedule: "@weekly"

discord:
  # Add a webhook URL to enable discord notifications.
  webhookURL: ""

ticketmaster:
  apiKey: "{TICKETMASTER_API_KEY_GOES_HERE}"
