name: concert-watcher
image: ryanconnell/concert-watcher:latest

cronSchedule: "@weekly"

discord:
  # Add a webhook URL to enable discord notifications.
  webhookURL: ""

ticketmaster:
  apiKey: "{TICKETMASTER_API_KEY_GOES_HERE}"
