name: concert-watcher
cronSchedule: "0 13 * * *"

image:
  name: ryanconnell/concert-watcher
  tag: latest

discord:
  # Add a webhook URL to enable discord notifications.
  webhookURL: ""

ticketmaster:
  apiKey: "{TICKETMASTER_API_KEY_GOES_HERE}"

storage:
  className: nfs-client
  size: 64Mi
